### ISSUE TITLE
register_table: RESTException: Unable to process: Failed to get subscoped credentials

### ISSUE THREAD

**Issue by ambaricloud** [apache/polaris#156]
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

Hi All
Able to create, and add data to the Polaris catalog/namespace table. Branching, FastFarward, and all maintenance procedures are working fine. In the Test Undo Drop Table use case, the below procedure failed. 

spark.sql("""CALL polaris.system.register_table(table => 'polaris.market.ksn’,metadata_file => 's3://<>/market/ksn/metadata/00001-b5616bb5-d382-4cd7-8ce3-235cd702c0c0.metadata.json')""")

py4j.protocol.Py4JJavaError: An error occurred while calling o76.sql.
: org.apache.iceberg.exceptions.RESTException: Unable to process: Failed to get subscoped credentials: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(sections=[])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Either the environment variable AWS_WEB_IDENTITY_TOKEN_FILE or the javaproperty aws.webIdentityTokenFile must be set., ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(sections=[])): Profile file contained no credentials for profile 'default': ProfileFile(sections=[]), ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Failed to load credentials from IMDS.].

**Comment by mayankvadariya** [comment]
Further stack trace.

```java
Caused by: org.apache.iceberg.exceptions.ServiceFailureException: Server error: SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(sections=[])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Either the environment variable AWS_WEB_IDENTITY_TOKEN_FILE or the javaproperty aws.webIdentityTokenFile must be set., ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(sections=[])): Profile file contained no credentials for profile 'default': ProfileFile(sections=[]), ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Failed to load credentials from IMDS.]
	at org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.accept(ErrorHandlers.java:217)
	at org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:118)
	at org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:102)
	at org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:211)
	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:323)
	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:262)
	at org.apache.iceberg.rest.HTTPClient.post(HTTPClient.java:368)
	at org.apache.iceberg.rest.RESTClient.post(RESTClient.java:112)
	at org.apache.iceberg.rest.RESTSessionCatalog.registerTable(RESTSessionCatalog.java:509)
```

**Comment by mayankvadariya** [comment]
Possibly `BaseMetastoreCatalog#registerTable` requires overridden in `BasePolarisCatalog` to have `BasePolarisCatalog#refreshIOWithCredentials` or `refreshCredentials` considered before making s3 call.

**Comment by dennishuo** [comment]
Thanks for the report! Indeed, it looks like the problem is that `registerTable` is the only thing in `BaseMetastoreCatalog` that tries to directly use the `ops.io()` immediately after building `ops = newTableOps(identifier)`.

Whereas other flows either deal with an existing Table entity and by calling `current()` will trigger a `doRefresh()` which will properly initialize the FileIO with StorageConfiguration-based credentials, or else will go through a `doCommit` which also initializes the FileIO with the right credentials, this `registerTable` flow will revert to the catalog's "default" FileIO.

The catalog's "default" FileIO is in some ways vestigial to make it easy for "Local FileSystem" based Java tests to work without having to mock out a fake credential-vending flow. We might want to refactor `BasePolarisCatalog` a bit to fast-fail if `BasePolarisTableOperations::io()` is ever used without being initialized with a `refreshIOWithCredentials` one way or another.

This will also require some consideration for how the `validateNoLocationOverlap` enforcement works, and also `validateLocationForTableLike` so that it can't be abused to load metadata JSON files residing outside of the StorageConfiguration's ALLOWED_LOCATIONS.

I'll try to draft a fix for this tomorrow.

**Comment by dennishuo** [comment]
Got a bit delayed from working on this, but I think I've at least gotten to a clear picture of how we might want to segregate scenarios for how callers can interact with `BasePolarisCatalog` to obtain a `FileIO` instance.

Mostly just thinking out loud here for posterity - one problem is that since we wanted to leverage `BaseMetastoreCatalog` to avoid re-implementing all the `TableOperations` logic, there's potential for conflating things that are supposed to happen logically on the "client-side" vs on the "service-side".

Basically we run the base Iceberg CatalogTests and View equivalents in two modes:

- `PolarisRestCatalogIntegrationTest` - end-to-end logic that plumbs `CatalogTests` through a `RESTSessionCatalog` so that `BasePolarisCatalog` is only ever used for "server-side" actions (e.g. only needs to interact with metadata JSON files)
- `BasePolarisCatalogTest` - directly points `CatalogTests` at the `BasePolarisCatalog` as if it's a traditional client-side-defined Iceberg catalog where "local" Transaction objects are used and `TableOperations::io()` is used for the FileIOs that potentially interact with manifest files and manifest-list files

Roughly, there are three categories of tests to consider:

1. Tests that use the `BasePolarisCatalog` to obtain a "client-local" FileIO -- these should either manually create a FileIO for pre-creating data or can go through a config setting that forces `BasePolarisCatalog` to create a "defaultFileIO" using `catalogProperties`.
2. Tests which go through the full REST plumbing but need the "server-side" Catalog to still use special or mocked FileIO settings. For example, `PolarisSparkIntegrationTest` uses `S3MockContainer` and needs to be able to set `s3.endpoint` int he catalog config
3. Tests which go through the full REST plumbing and fully cooperate with "standard" credential-vending semantics and/or use only `file:///` paths. These should work without needing to fall back to `catalogProperties` nor rely on `defaultFileIO`

Right now these rely on a lot of silent fallthrough behaviors, but we should make them more explicit. Supporting (2) more explicitly may also be the key to supporting https://github.com/apache/polaris/issues/69 in a cleaner way.

**Comment by ambaricloud** [comment]
Can we test this in snowflake-managed Polaris account?
