### ISSUE TITLE
Polaris not starting up / `TaskHandlerConfiguration` not JSON-serializable

### ISSUE THREAD

**Issue by snazy** [apache/polaris#561]
### Describe the bug

Polaris startup fails with

```
java.lang.IllegalArgumentException: Unable to create an instance of the configuration class: 'org.apache.polaris.service.dropwizard.config.PolarisApplicationConfig'
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:125)
        at io.dropwizard.core.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:141)
        at io.dropwizard.core.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.core.cli.Cli.run(Cli.java:78)
        at io.dropwizard.core.Application.run(Application.java:94)
        at org.apache.polaris.service.dropwizard.PolarisApplication.main(PolarisApplication.java:153)
Caused by: java.lang.IllegalArgumentException: No serializer found for class org.apache.polaris.service.config.TaskHandlerConfiguration and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.apache.polaris.service.dropwizard.config.PolarisApplicationConfig["taskHandler"])
        at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:3614)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:120)
        ... 5 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.apache.polaris.service.config.TaskHandlerConfiguration and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.apache.polaris.service.dropwizard.config.PolarisApplicationConfig["taskHandler"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
        at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1328)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:53)
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:30)
        at com.fasterxml.jackson.module.blackbird.ser.ObjectPropertyWriter.serializeAsField(ObjectPropertyWriter.java:97)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:184)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
        at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:3609)
        ... 6 more
```

### To Reproduce

`./gradlew :polaris-dropwizard-service:runApp --args bootstrap`

**Comment by jbonofre** [comment]
It's a duplicated from #542 that gathers binary distribution startup issues.

**Comment by snazy** [comment]
This is different from #542, right?

**Comment by jbonofre** [comment]
Yes and no: #542 is about to gather all related startup issues, including this one.

**Comment by jbonofre** [comment]
No problem if you want to reopen, but I kindly ask to update the title to describe the actual issue.

**Comment by dimas-b** [comment]
This is a peculiarity of YAML config parsing in DW. It works fine if the config file is specified.

```
./gradlew :polaris-dropwizard-service:runApp --args "bootstrap ../../polaris-server.yml"
```

**Comment by adutra** [comment]
@dimas-b is right: this issue but also #580, #560, #561, #562, only happen when no config file is specified. I think it's mandatory to provide one, only the scripts do not print a clear message saying that the config file wasn't specified.

**Comment by adutra** [comment]
I think we should not consider the above mentioned issues as release blockers.

**Comment by snazy** [comment]
Fixed via #469
