### ISSUE TITLE
Bootstrap fails w/ NPE - `PolarisApplicationConfig.serviceLocator` is `null`

### ISSUE THREAD

**Issue by snazy** [apache/polaris#580]
### Describe the bug

After adding fixes for #560, #561, #562, there's another new NPE that prevents `bootstrap` w/ eclipselink:

```
java.lang.NullPointerException: Cannot invoke "org.glassfish.hk2.api.ServiceLocator.getService(java.lang.Class, java.lang.annotation.Annotation[])" because "this.serviceLocator" is null
        at org.apache.polaris.service.dropwizard.config.PolarisApplicationConfig.findService(PolarisApplicationConfig.java:189)
	at org.apache.polaris.service.dropwizard.BootstrapRealmsCommand.run(BootstrapRealmsCommand.java:50)
	at org.apache.polaris.service.dropwizard.BootstrapRealmsCommand.run(BootstrapRealmsCommand.java:37)
	at io.dropwizard.core.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.core.cli.Cli.run(Cli.java:78)
	at io.dropwizard.core.Application.run(Application.java:94)
	at org.apache.polaris.service.dropwizard.PolarisApplication.main(PolarisApplication.java:154)
```

I'm not sure whether it's worth to fix all these issues but instead wait for #469.

**Comment by snazy** [comment]
Likely superseded by #469
